# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/category.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from math import ceil
from item import test_item

class Ui_Dialog(object):
    def setupUi(self, Dialog, category_name, items):
        _translate = QtCore.QCoreApplication.translate

        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(860, 770)
        Dialog.setWindowTitle(_translate("Dialog", "Shalqam - Category Page"))

        # Dialog = QtWidgets.QWidget(Dialog)
        # Dialog.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")

        # Creating category label at the top of the page
        self.category_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.category_label.setFont(font)
        self.category_label.setStyleSheet("QLabel{ width: 100%; height: 55px; background-color: #CA80DC; border-radius: 15px; padding: 0 35px 0 35px; color: #fff; line-height: 1.2;}")
        self.category_label.setAlignment(QtCore.Qt.AlignCenter)
        self.category_label.setObjectName("category_label")
        self.category_label.setText(_translate("Dialog", category_name))

        self.verticalLayout.addWidget(self.category_label)

        # Scroll area definition
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 594, 561))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")


        # Creating grid layout for items
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")

        self.verticalLayouts = []
        self.item_labels = []
        #        self.pushButton = QPushButton(self.scrollAreaWidgetContents)
        
        cols = 4
        rows = ceil(len(items) / cols)
        positions = [(i, j) for i in range(rows) for j in range(cols)]

        for (position, item) in zip(positions, items):
            verticalLayout = QtWidgets.QVBoxLayout()
            
            item_name_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            item_name_label.setText(_translate("Dialog", item.name))
            item_name_label.setAlignment(QtCore.Qt.AlignCenter)

            item_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            item_label.setPixmap(QtGui.QPixmap(item.getImage()))
            
            item_price_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            item_price_label.setText(_translate("Dialog", str(item.price)))
            item_price_label.setAlignment(QtCore.Qt.AlignCenter)

            verticalLayout.addWidget(item_name_label)
            verticalLayout.addWidget(item_label)
            verticalLayout.addWidget(item_price_label)

            self.gridLayout.addLayout(verticalLayout, *position)
            self.item_labels.append(item_label)

        # self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        # self.verticalLayout_3.setObjectName("verticalLayout_3")

        # self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.label_8.setObjectName("label_8")
        # self.verticalLayout_3.addWidget(self.label_8)
        # self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.label_9.setObjectName("label_9")
        # self.verticalLayout_3.addWidget(self.label_9)
        # self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.label_10.setObjectName("label_10")
        # self.verticalLayout_3.addWidget(self.label_10)

        # self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        # Dialog.setCentralWidget(Dialog)

        # self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # def retranslateUi(self, Dialog):
    #     _translate = QtCore.QCoreApplication.translate
    #     Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    #     self.category_label.setText(_translate("Dialog", "Category"))
    #     self.label_8.setText(_translate("Dialog", "TextLabel"))
    #     self.label_9.setText(_translate("Dialog", "TextLabel"))
    #     self.label_10.setText(_translate("Dialog", "TextLabel"))
    #     self.label_11.setText(_translate("Dialog", "TextLabel"))
    #     self.label_12.setText(_translate("Dialog", "TextLabel"))
    #     self.label_13.setText(_translate("Dialog", "TextLabel"))
    #     self.label_5.setText(_translate("Dialog", "TextLabel"))
    #     self.label_6.setText(_translate("Dialog", "TextLabel"))
    #     self.label_7.setText(_translate("Dialog", "TextLabel"))
    #     self.label_2.setText(_translate("Dialog", "TextLabel"))
    #     self.label_3.setText(_translate("Dialog", "TextLabel"))
    #     self.label_4.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, test_item.category, [test_item])
    Dialog.show()
    sys.exit(app.exec_())
