# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\resources/shalqam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.login_message_Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.login_message_Label.setFont(font)
        self.login_message_Label.setStyleSheet("QLabel{\n"
"    width: 100%;\n"
"    height: 50px;\n"
"    background-color: #CA80DC;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"    color: #fff;\n"
"    line-height: 1.2;\n"
"}")
        self.login_message_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_message_Label.setObjectName("login_message_Label")
        self.verticalLayout_4.addWidget(self.login_message_Label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(14)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout.addWidget(self.username_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(14)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.login_pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setStyleSheet("QPushButton{\n"
"    padding: 0 20px;\n"
"    width: 100%;\n"
"    height: 50px;\n"
"    background-color: #57b846;\n"
"    border-radius: 25px;\n"
"    color: #fff;\n"
"    line-height: 1.2;\n"
"}\n"
"")
        self.login_pushButton.setObjectName("login_pushButton")
        self.verticalLayout_3.addWidget(self.login_pushButton)
        self.signup_pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.signup_pushButton.setFont(font)
        self.signup_pushButton.setStyleSheet("QPushButton#signup_pushButton{\n"
"    padding: 0 20px;\n"
"    width: 100%;\n"
"    height: 50px;\n"
"    background-color: #57b846;\n"
"    border-radius: 25px;\n"
"    color: #fff;\n"
"    line-height: 1.2;\n"
"}")
        self.signup_pushButton.setObjectName("signup_pushButton")
        self.verticalLayout_3.addWidget(self.signup_pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login_message_Label.setText(_translate("Dialog", "Sign in to \n"
"Your Account"))
        self.username_lineEdit.setPlaceholderText(_translate("Dialog", "Username"))
        self.password_lineEdit.setPlaceholderText(_translate("Dialog", "Password"))
        self.login_pushButton.setText(_translate("Dialog", "Login"))
        self.signup_pushButton.setText(_translate("Dialog", "SignUp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
