# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 419)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\resources/shalqam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.createAccount_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.createAccount_label.setFont(font)
        self.createAccount_label.setAlignment(QtCore.Qt.AlignCenter)
        self.createAccount_label.setObjectName("createAccount_label")
        self.verticalLayout_3.addWidget(self.createAccount_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.firstName_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.firstName_lineEdit.setFont(font)
        self.firstName_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.firstName_lineEdit.setInputMask("")
        self.firstName_lineEdit.setText("")
        self.firstName_lineEdit.setMaxLength(32767)
        self.firstName_lineEdit.setFrame(True)
        self.firstName_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.firstName_lineEdit.setObjectName("firstName_lineEdit")
        self.horizontalLayout_2.addWidget(self.firstName_lineEdit)
        self.lastName_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(12)
        self.lastName_lineEdit.setFont(font)
        self.lastName_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.lastName_lineEdit.setObjectName("lastName_lineEdit")
        self.horizontalLayout_2.addWidget(self.lastName_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.username_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab Medium")
        font.setPointSize(14)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout.addWidget(self.username_lineEdit)
        self.email_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(14)
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout.addWidget(self.email_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(14)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.repeatPassword_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(14)
        self.repeatPassword_lineEdit.setFont(font)
        self.repeatPassword_lineEdit.setStyleSheet("QLineEdit{\n"
"    color: #1b3815;\n"
"    line-height: 1.2;\n"
"    position: relative;\n"
"    width: 100%;\n"
"    height: 55px;\n"
"    background: #ebebeb;\n"
"    border-radius: 27px;\n"
"    padding: 0 35px 0 35px;\n"
"}")
        self.repeatPassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeatPassword_lineEdit.setObjectName("repeatPassword_lineEdit")
        self.verticalLayout.addWidget(self.repeatPassword_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.signup_pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.signup_pushButton.setFont(font)
        self.signup_pushButton.setStyleSheet("QPushButton{\n"
"    padding: 0 20px;\n"
"    width: 100%;\n"
"    height: 50px;\n"
"    background-color: #57b846;\n"
"    border-radius: 25px;\n"
"    color: #fff;\n"
"    line-height: 1.2;\n"
"}")
        self.signup_pushButton.setObjectName("signup_pushButton")
        self.verticalLayout_3.addWidget(self.signup_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.createAccount_label.setText(_translate("Dialog", "Create Account"))
        self.firstName_lineEdit.setPlaceholderText(_translate("Dialog", "First Name"))
        self.lastName_lineEdit.setPlaceholderText(_translate("Dialog", "Last Name"))
        self.username_lineEdit.setPlaceholderText(_translate("Dialog", "Username"))
        self.email_lineEdit.setPlaceholderText(_translate("Dialog", "Email address"))
        self.password_lineEdit.setPlaceholderText(_translate("Dialog", "Password"))
        self.repeatPassword_lineEdit.setPlaceholderText(_translate("Dialog", "Repeat Password"))
        self.signup_pushButton.setText(_translate("Dialog", "SignUp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
