from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\resources/shalqam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.login_message_Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.login_message_Label.setFont(font)
        self.login_message_Label.setStyleSheet("QLabel{ width: 100%; height: 50px; background-color: #CA80DC; border-radius: 27px; padding: 0 35px 0 35px; color: #fff; line-height: 1.2;}")
        self.login_message_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.login_message_Label.setObjectName("login_message_Label")
        self.verticalLayout_4.addWidget(self.login_message_Label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.username_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(14)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("QLineEdit{ color: #1b3815; line-height: 1.2; position: relative; width: 100%; height: 55px; background: #ebebeb; border-radius: 27px; padding: 0 35px 0 35px;}")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout.addWidget(self.username_lineEdit)
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(14)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setStyleSheet("QLineEdit{ color: #1b3815; line-height: 1.2; position: relative; width: 100%; height: 55px; background: #ebebeb; border-radius: 27px; padding: 0 35px 0 35px;}")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout.addWidget(self.password_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.login_pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setStyleSheet("QPushButton{ padding: 0 20px; width: 100%; height: 50px; background-color: #57b846; border-radius: 25px; color: #fff; line-height: 1.2;}")
        self.login_pushButton.setObjectName("login_pushButton")
        self.verticalLayout_3.addWidget(self.login_pushButton)
        self.signup_pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Josefin Slab")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.signup_pushButton.setFont(font)
        self.signup_pushButton.setStyleSheet("QPushButton#signup_pushButton{ padding: 0 20px; width: 100%; height: 50px; background-color: #57b846; border-radius: 25px; color: #fff; line-height: 1.2;}")
        self.signup_pushButton.setObjectName("signup_pushButton")
        self.verticalLayout_3.addWidget(self.signup_pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Shalqam - Login Page"))
        self.login_message_Label.setText(_translate("Dialog", "Sign in to \nYour Account"))
        self.username_lineEdit.setPlaceholderText(_translate("Dialog", "Username"))
        self.password_lineEdit.setPlaceholderText(_translate("Dialog", "Password"))
        self.login_pushButton.setText(_translate("Dialog", "Login"))
        self.signup_pushButton.setText(_translate("Dialog", "SignUp"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
